"""create users and financial profiles

Revision ID: 6d331b0a5359
Revises: 7c60f9d7bb8b
Create Date: 2026-03-24 17:49:34.027490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d331b0a5359'
down_revision: Union[str, None] = '7c60f9d7bb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
